{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.persistence.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.persistence.storageClass | quote }}
  {{ else }}
  storageClassName: ""
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.useDynamicProvisioning  }}
  selector:
    matchLabels:
      assign-to: "openldap"
  {{- end }}
{{- end }}


