name: ibm-kibana
version: 0.10.0
appVersion: 6.3.1
description: Kibana is an open source data visualization plugin for Elasticsearch
icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
keywords:
- elasticsearch
- kibana
- Limited
- ppc64le
- Tools
- ICP
maintainers:
- name: IBM ISV Team
  email: smohite@us.ibm.com
sources:
- https://github.com/elastic/kibana
engine: gotpl
home: https://www.elastic.co/products/kibana
tillerVersion: '>=2.7.2'
