apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "metrics-server.fullname" . }}
  labels:
    app: {{ template "metrics-server.name" . }}
    chart: {{ template "metrics-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "metrics-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "metrics-server.name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "metrics-server.chart" . }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ template "metrics-server.serviceAccountName" . }}
      containers:
        - name: metrics-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /metrics-server
            - --source=kubernetes.summary_api:https://kubernetes.default.svc?kubeletHttps=true&kubeletPort=10250&insecure=true
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}

{{- end }}

