{{- if gt (len .Values.daemonset.config.outputs.influxdb.urls) 0 }}
{{- if .Values.daemonset.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-ds
  labels:
    app: {{ template "fullname" . }}-ds
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  telegraf.conf: |+
    {{ template "globalTags" .Values.daemonset.config.globalTags }}
    {{ template "agent" .Values.daemonset.config.agent }}
    {{ template "outputs" .Values.daemonset.config.outputs }}
    {{ template "inputs" .Values.daemonset.config.inputs -}}
{{- end -}}
{{- end -}}
