#container specification

image:
  name: open-liberty
  tag: kernel
  pullPolicy: IfNotPresent

# service specification
service:
  type: NodePort
  port: 9080
#Resource specification
resources:
  requests:
    memory: 200Mi
    cpu: 100m

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - ghost.local
  tls: []

node: "ppc64le"
