node:
   __metadata:
     name: "Node"
     label: "nodeSelector"
     description: "Node Prefernce"
     type: "string"
     immutable: "false"
     required: true
     options:
     - label: "ppc64le"
       value: "ppc64le"
