apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rstudio.fullname" . }}
  labels:
    app: {{ template "rstudio.name" . }}
    chart: {{ template "rstudio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rstudio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rstudio.name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "rstudio.chart" . }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh","-c","set -e && useradd -m -d /home/test test && echo test:test | chpasswd; rstudio-server online;/usr/sbin/rstudio-server start;sleep infinity;"]
          ports:
          - name: http
            containerPort: 8787
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
{{- end }}

