apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openliberty.fullname" . }}
  labels:
    app: "{{ template "openliberty.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

data:
  myvalue: "Open Liberty"
