apiVersion: v1
kind: Service
metadata:
  name: {{ template "openliberty.fullname" . }}
  labels:
    app: {{ template "openliberty.name" . }}
    chart: {{ template "open-liberty.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9080
      name: http
    - port: 9443
      name: https
      targetPort: http
      protocol: TCP     
  selector:
    app: {{ template "openliberty.name" . }}
    release: {{ .Release.Name }}
