apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "strongloop.fullname" . }}
  labels:
    app: {{ template "strongloop.name" . }}
    chart: {{ template "strongloop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "strongloop.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "strongloop.name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "strongloop.chart" . }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 41629
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
{{- end }}

