{{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "lamp.fullname" . }}
  labels:
    app: {{ template "lamp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.persistence.keep }}
    helm.sh/resource-policy: keep
  {{- end }}

spec:
  {{- if .Values.persistence.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.persistence.storageClass | quote }}
  {{ else }}
  storageClassName: ""
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.useDynamicProvisioning  }}
  selector:
    matchLabels:
      assign-to: "ibm-lamp"
  {{- end }}
{{- end }}

