apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "etcd.fullname" . }}
  labels:
    app: {{ template "etcd.name" . }}
    chart: {{ template "etcd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "etcd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "etcd.name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "etcd.chart" . }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 2380
          - containerPort: 2379
          command: ["/bin/sh","-c"]
          args: ["/usr/local/bin/etcd -advertise-client-urls 'http://0.0.0.0:2380' -listen-client-urls 'http://0.0.0.0:2379'"]
          livenessProbe:
            tcpSocket:
              port: 2379
          readinessProbe:
            tcpSocket:
              port: 2379
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
{{- end }}

